const { SUPPORT_CONTACT } = require('./config');

// ==================== MESSAGE TEMPLATES ====================

const messages = {
  start: () => `🚀 *Number Lookup Bot*

_Welcome to the number information bot._

_Send any *10–15 digit phone number* to get details such as:_

• _owner name_
• _father name_
• _address_
• _carrier / circle_
• _alternate number_
• _email (if available)_

_Example:_
\`9876543210\`

⚡ _Fast results • Clean format_

🛠 *Support:* _${SUPPORT_CONTACT}_`,

  forceJoin: () => `🚫 *Access Restricted*

_To use this bot you must join all required channels._

_After joining press_ *✅ I Joined*`,

  invalidNumber: () => `⚠️ *Invalid Number*

_The number you entered is not valid._

_Please send a proper *10–15 digit phone number*._

_Example:_
\`9876543210\``,

  noRecord: () => `🔍 *No Record Found*

_This number was not found in the database._

_Possible reasons:_

• _The number is not available in the dataset_
• _The number was recently registered_
• _No public records exist_

_You can try checking another number._`,

  serviceError: () => `⚠️ *Service Error*

_The lookup service is temporarily unavailable._

_Please try again in a few minutes._`,

  adminPanel: (totalUsers) => `👑 *Admin Panel*

_Manage bot settings and users._

📊 *Total Users:* _${totalUsers}_

_Select an action below:_`,

  userBanned: (userId) => `🚫 *User Banned*

_User ID_ \`${userId}\` _has been banned from using the bot._`,

  userUnbanned: (userId) => `✅ *User Unbanned*

_User ID_ \`${userId}\` _can now use the bot again._`,

  broadcastSent: (count) => `📢 *Broadcast Sent*

_Message delivered to_ *${count}* _users._`,

  youAreBanned: () => `🚫 *Access Denied*

_You have been banned from using this bot._

_Contact_ ${SUPPORT_CONTACT} _for support._`
};

// ==================== UTILITY FUNCTIONS ====================

// Parse address from API format (separated by !)
function parseAddress(addressStr) {
  if (!addressStr) return [];
  const parts = addressStr.split('!').filter(p => p && p.trim());
  return parts.map(p => p.trim());
}

// Format lookup result with proper Markdown
function formatLookupResult(data, index = null) {
  const header = index !== null ? `🔎 *Result ${index}*\n\n` : `🔎 *Number Lookup Result*\n\n`;
  
  let result = header;
  
  // Phone number (API uses 'mobile')
  if (data.mobile || data.number || data.phone) {
    const num = data.mobile || data.number || data.phone;
    result += `_📱 *Number:* \`${num}\`_\n\n`;
  }
  
  // Name
  if (data.name && data.name.trim()) {
    result += `_👤 *Name:* ${data.name}_\n`;
  }
  
  // Father name (API uses 'fname')
  if ((data.fname || data.fatherName) && (data.fname || data.fatherName).trim()) {
    result += `_👨‍👦 *Father Name:* ${data.fname || data.fatherName}_\n`;
  }
  
  // Carrier/Circle (API uses 'circle')
  if ((data.circle || data.carrier) && (data.circle || data.carrier).trim()) {
    result += `\n_📡 *Carrier:* ${data.circle || data.carrier}_\n`;
  }
  
  // Address (API format: separated by !)
  const addressParts = parseAddress(data.address);
  
  if (addressParts.length > 0) {
    result += `\n🏠 *Address*\n\n`;
    addressParts.forEach(part => {
      result += `_${part}_\n`;
    });
  }
  
  // Alternate number (API uses 'alt')
  if ((data.alt || data.altNumber) && (data.alt || data.altNumber).trim()) {
    const altNum = data.alt || data.altNumber;
    result += `\n_☎️ *Alternate Number:* \`${altNum}\`_\n`;
  }
  
  // Email (only show if exists and not null)
  if (data.email && data.email.trim()) {
    result += `\n_📧 *Email:* ${data.email}_\n`;
  }
  
  if (index === null) {
    result += `\n━━━━━━━━━━━━━━\n\n_⚡ Result generated by the Number Lookup Bot_`;
  }
  
  return result;
}

// Validate phone number (10-15 digits)
function isValidNumber(text) {
  const cleaned = text.replace(/\D/g, '');
  return cleaned.length >= 10 && cleaned.length <= 15;
}

// Clean phone number (remove non-digits)
function cleanNumber(text) {
  return text.replace(/\D/g, '');
}

module.exports = {
  messages,
  parseAddress,
  formatLookupResult,
  isValidNumber,
  cleanNumber
};
